sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t gzeromin/test-react -f Dockerfile.dev ./

script:
  - docker run -e CI=true gzeromin/test-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "test-docker-react"
  env: "Testdockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-571424513975"
  bucket_path: "test-docker-react"
  on:
    branch: main
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY